- name: Compute Engine IVA-IPS Network
  hosts: localhost
  vars_files:
    - ../gce_vars/auth
    - ../infra_vars/network-prod
  tasks:
      - name: Create IVA-IPS network
        gce_net:
          name: "{{ iva_ips_network_name }}"
          mode: auto
          state: "present"
          project_id: "{{ project_id }}"
          credentials_file: "{{ credentials_file }}"
          service_account_email: "{{ service_account_email }}"
        register: result
      - name: "assert network created"
        assert:
          that:
            - 'result.state == "present"'
      - name: Create SSH Firewall Rule
        gce_net:
          name: "{{ iva_ips_network_name }}"
          fwname: "{{ iva_ips_fw_ssh_name }}"
          allowed: tcp:22;icmp
          state: "present"
          src_tags: "{{ iva_ips_fw_ssh_src_tags }}"
          target_tags: "{{ iva_ips_fw_ssh_target_tags }}"
          project_id: "{{ project_id }}"
          credentials_file: "{{ credentials_file }}"
          service_account_email: "{{ service_account_email }}"
        register: result
      - name: "assert fw created"
        assert:
          that:
            - 'result.state == "present"'
