- name: Tear down Global IVA Space Site
  hosts: localhost
  vars_files:
    - gce_vars/auth
    - app_vars/iva-prod
  tasks:
    # ============================================================
    # Delete Global Forwarding Rule
    # ============================================================
    - name: Delete Global Forwarding Rule
      gcp_forwarding_rule:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: "{{ gfr }}"
        target: "{{ targethttpproxy }}"
        address: "{{ external_address_name }}"
        port_range: 80
        region: global
        state: "absent"
      register: result
      ignore_errors: true
    - name: "assert gfr absent"
      assert:
        that:
          - 'result.state == "absent"'
    # ============================================================
    # Delete Static Address
    # ============================================================
    - name: Delete Static Address
      gce_eip:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: "{{ external_address_name }}"
        region: global
        state: "absent"
      register: result
      ignore_errors: true
    - name: "assert static address absent"
      assert:
        that:
#          - 'result.changed'
          - 'result.state == "absent"'

    # ============================================================
    # Delete TargetProxy
    # ============================================================
    - name: Delete TargetHTTPProxy
      gcp_target_proxy:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: "{{ targethttpproxy }}"
        urlmap: "{{ urlmap }}"
        state: "absent"
      register: result
      ignore_errors: true
    - name: "assert targethttpproxy absent"
      assert:
        that:
#          - 'result.changed'
          - 'result.state == "absent"'

    # ============================================================
    # Delete URLMap
    # ============================================================
    - name: Delete URLMap
      gcp_url_map:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        url_map_name: "{{ urlmap }}"
        default_service: "{{ bes }}"
        state: "absent"
      register: result
      ignore_errors: true
    - name: "assert urlmap absent"
      assert:
        that:
          - 'result.state == "absent"'
    - pause: seconds=10

    # ============================================================
    # Delete Backend Service
    # ============================================================
    - name: Delete BES
      gcp_backend_service:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        backend_service_name: "{{ bes }}"
        backends:
          - instance_group: "{{ mig_one }}"
          - instance_group: "{{ mig_two }}"
        healthchecks:
          - "{{ bes_healthcheck }}"
        port_name: "{{ http_port_name }}"
        protocol: HTTP
        timeout: 60
        state: "absent"
      register: result
    - name: "assert backend service absent"
      assert:
        that:
          # - 'result.changed'
          - 'result.state == "absent"'
    # ============================================================
    # Delete MIG one
    # ============================================================
    - name: Delete MIG one
      gce_mig:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: "{{ mig_one }}"
        zone: "{{ mig_one_zone }}"
        state: "absent"
        size: 1
        template: "{{ instance_template }}"
        named_ports:
          - name: "{{ http_port_name }}"
            port: "{{ http_port }}"
        autoscaling:
          enabled: yes
          name: "{{ mig_one }}"
          policy:
            min_instances: 2
            max_instances: 10
            cool_down_period: 30
            cpu_utilization:
              target: 0.02
    # ============================================================
    # Delete MIG two
    # ============================================================
    - name: Delete MIG two
      gce_mig:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: "{{ mig_two }}"
        zone: "{{ mig_two_zone }}"
        state: "absent"
        size: 1
        template: "{{ instance_template }}"
        named_ports:
          - name: "{{ http_port_name }}"
            port: "{{ http_port }}"
        autoscaling:
          enabled: yes
          name: "{{ mig_two }}"
          policy:
            min_instances: 2
            max_instances: 10
            cool_down_period: 30
            cpu_utilization:
              target: 0.02
