---
# play: launch GCE VMs
- name: Create Compute Engine instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zonea
  tasks:
    - name: Bring up the instances for testing
      gce:
        instance_names: "{{ names_zonea }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ zonea }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      register: gcea
  post_tasks:
    - name: Ensure SSH is available
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ gcea.instance_data }}"
    - name: Save host data
      add_host: hostname={{ item.public_ip }} groupname=camera_test_instances
      with_items: "{{ gcea.instance_data }}"
