---
# Execute the params on multiple hosts and ensure they call pass
- name: Run camera param test
  hosts: camera_test_instances
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/zonea
    - app_vars/camera-test
  tasks:
    - name: "Run test"
      command: '/usr/local/bin/test-camera-params camA="{{cameraA}}" camB="{{cameraB}}" camC="{{cameraC}}"'
      register: result
    - name: debug
      debug:
        var: result
        verbosity: 2
    - name: assert all hosts passed
      assert:
        that:
          - 'result.changed'
          - "'passed successfully' in result.stdout"
          - 'result.stdout_lines|length == 5'
        

