---
# compute-video-demo-ansible
- name: Destroy all demo resources
  hosts: localhost
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zonea
  tasks:
    - name: Destroy the instances in the first zone
      gce:
        instance_names: "{{ names_zonea }}"
        zone: "{{ zonea }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: absent